ICM-2938
InsiteSoftware/commerce-csharp-sdk pull request #117
Opened 2023-05-26 10:32 UTC by anisuroptimizely

2023-05-26 13:16 UTC, anayaian requested changes

2023-05-26 13:16 UTC, anayaian commented on CommerceApiSDK/CommerceApiSDK.csproj
> +    <ReleaseVersion>3.1.2</ReleaseVersion>
Please remove this @anisuroptimizely

2023-05-29 08:37 UTC, anisuroptimizely commented on CommerceApiSDK/CommerceApiSDK.csproj
> +    <ReleaseVersion>3.1.2</ReleaseVersion>
Removed @anayaian vai

2023-05-29 09:38 UTC, anayaian approved these changes

2023-05-29 12:05 UTC, anayaian approved these changes

2023-05-29 12:05 UTC, merged